#!/usr/bin/env bash
#transfer file to server via scp

# Check if all 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Check if the file exists
if [ ! -f "$file_path" ]; then
    echo "Error: File not found at $file_path"
    exit 1
fi

# Transfer the file using SCP
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
