#!/usr/bin/env bash
#+    Listens on port 80.
#+    Returns a page containing "Hello World" when queried
#+     at the root with a curl GET request.
#+    Configures /redirect_me as a "301 Moved Permanently".
#+    Includes a custom 404 page containing "Ceci n'est pas une page".
#+    Contains a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo chmod 777 /var/www/html/index.html
sudo chmod 777 /etc/nginx/sites-available/default

sudo echo "Hello World" > /var/www/html/index.html

sudo echo 'server {
                listen 80 default_server;
                root /var/www/html;
                index index.html index.htm;
                add_header X-Served-By $HOSTNAME;

                location /{
                        try_files $uri $uri/ =404;
        }
}' > /etc/nginx/sites-available/default
sudo service nginx restart
