#!/usr/bin/env bash
# a custom header
#
balancer='


frontend fe
    bind *:80
    mode http
    default_backend be
    
backend be
    balance roundrobin
    server 515069-web-01 54.160.104.88:80 check
    server 515069-web-02 34.224.15.78:80 check
'
# Update packages
sudo apt-get -y update

# Install HAProxy
sudo apt -y install haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
