#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
function sigquit
{
rm /var/run/myscript.pid
exit
}
function sigterm
{
echo "I hate the kill command"
rm /var/run/myscript.pid
exit
}
trap 'sigterm' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sigquit' SIGQUIT
touch /var/run/myscript.pid
echo "$$" >> /var/run/myscript.pid
while true
do
echo "To infinity and beyond"
sleep 2
done
